version: '3.9'
networks:
  node-desafio:
    driver: bridge
services:
  db:
    image: postgres
    container_name: node-postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - node-desafio
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - APP_DB_NAME=node
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./app/sql/create_banco.sql:/docker-entrypoint-initdb.d/create_banco.sql/
    expose:
      - 5432
  app:
    container_name: desafio-node
    image: nosdeedson/desafio-node:latest
    links: 
      - db
    networks:
      - node-desafio
    ports:
      - 8080:80
    depends_on:
      - db
    expose:
      - 8080
volumes:
  local_pgdata: